# Generated by Django 2.2.26 on 2022-01-06 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('profile', models.CharField(blank=True, max_length=200, null=True, verbose_name='プロフィール')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'db_table': 'api_user',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Live_stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='タイトル')),
                ('started_at', models.DateField(default=django.utils.timezone.now, verbose_name='日時')),
                ('live_url', models.CharField(max_length=2000, null=True, verbose_name='ライブ視聴URL')),
                ('ticket_url', models.CharField(max_length=2000, null=True, verbose_name='ライブチケット購入URL')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=200, verbose_name='チケット番号')),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Live_stream', verbose_name='ライブ')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='内容')),
                ('posted_at', models.DateField(default=django.utils.timezone.now)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='書いたユーザー')),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Live_stream', verbose_name='ライブ配信')),
                ('reply_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Post', verbose_name='リプライ先投稿')),
            ],
        ),
        migrations.CreateModel(
            name='Live_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Live_stream', verbose_name='ライブ配信')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Live_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200, verbose_name='画像名')),
                ('data', models.TextField(verbose_name='画像データ')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Post', verbose_name='投稿')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Post', verbose_name='投稿')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='書いたユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_follow', to=settings.AUTH_USER_MODEL, verbose_name='フォロー先')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL, verbose_name='フォロー元')),
            ],
        ),
        migrations.CreateModel(
            name='Dm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='内容')),
                ('sent_at', models.DateField(default=django.utils.timezone.now, verbose_name='書き込み時刻')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dm_receiver', to=settings.AUTH_USER_MODEL, verbose_name='送信先ユーザー')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dm_sender', to=settings.AUTH_USER_MODEL, verbose_name='書いたユーザー')),
            ],
        ),
    ]
