# Generated by Django 2.2.26 on 2022-01-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220107_1740'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'follow'), name='unique_follow'),
        ),
    ]
