# Generated by Django 2.2.26 on 2022-01-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220107_1912'),
        ('api', '0002_auto_20220107_1710'),
    ]

    operations = [
    ]
