# Generated by Django 2.2.26 on 2022-01-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220107_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reply_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Post', verbose_name='リプライ先投稿'),
        ),
    ]
