# Generated by Django 2.2.26 on 2022-01-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_live_picture_image_name'),
        ('api', '0005_merge_20220107_2031'),
    ]

    operations = [
    ]
