# Generated by Django 2.2.26 on 2022-01-08 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20220107_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='書き込み時刻'),
        ),
        migrations.AlterField(
            model_name='live_stream',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日時'),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
